prod:
  mrf:
    mos:
      role_auth_data:
        admin_mrf:
          email: "TestHotezaHotelAdmin"
          password: "123456Qwerty!"

        admin_hotel:
          email: ""
          password: ""

        employee:
          email: ""
          password: ""

    ural:
      role_auth_data:
        admin_mrf:
          email: ""
          password: ""

        admin_hotel:
          email: ""
          password: ""

        employee:
          email: ""
          password: ""

    ct:
      role_auth_data:
        admin_mrf:
          email: ""
          password: ""

        admin_hotel:
          email: ""
          password: ""

        employee:
          email: ""
          password: ""

    volga:
      role_auth_data:
        admin_mrf:
          email: ""
          password: ""

        admin_hotel:
          email: ""
          password: ""

        employee:
          email: ""
          password: ""

    sibir:
      role_auth_data:
        admin_mrf:
          email: ""
          password: ""

        admin_hotel:
          email: ""
          password: ""

        employee:
          email: ""
          password: ""

    fe:
      role_auth_data:
        admin_mrf:
          email: ""
          password: ""

        admin_hotel:
          email: ""
          password: ""

        employee:
          email: ""
          password: ""

    south:
      role_auth_data:
        admin_mrf:
          email: ""
          password: ""

        admin_hotel:
          email: ""
          password: ""

        employee:
          email: ""
          password: ""

    nw:
      role_auth_data:
        admin_mrf:
          email: ""
          password: ""

        admin_hotel:
          email: ""
          password: ""

        employee:
          email: ""
          password: ""

test:
  mrf:
    mos:
      role_auth_data:
        admin_mrf:
          email: ""
          password: ""

        admin_hotel:
          email: ""
          password: ""

        employee:
          email: ""
          password: ""

    ural:
      role_auth_data:
        admin_mrf:
          email: ""
          password: ""

        admin_hotel:
          email: ""
          password: ""

        employee:
          email: ""
          password: ""

    ct:
      sdp_auth_data:
        login: "test_htm_admin"
        password: "q1w2e3r4t5y6"
        language: "ru"

      role_auth_data:
        admin_mrf:
          email: "ct-admin@rt.ru"
          password: "123456ct"
          id: 1

        main_hotel_users:
          admin_hotel:
            email: "test_htm_api@test.test"
            password: "Q1w2e3r4t5y6!"
            id: 74

          employee:
            email: "employee_test_htm_api@test.test"
            password: "Q1w2e3r4t5y6!"
            id: 76

        second_hotel_users:
          admin_hotel:
            email: "second_admin_hotel_test_htm_api@test.test"
            password: "Q1w2e3r4t5y6!"
            id: 93

          employee:
            email: "second_employee_test_htm_api@test.test"
            password: "Q1w2e3r4t5y6!"
            id: 94

    volga:
      role_auth_data:
        admin_mrf:
          email: ""
          password: ""

        admin_hotel:
          email: ""
          password: ""

        employee:
          email: ""
          password: ""

    sibir:
      role_auth_data:
        admin_mrf:
          email: ""
          password: ""

        admin_hotel:
          email: ""
          password: ""

        employee:
          email: ""
          password: ""

    fe:
      role_auth_data:
        admin_mrf:
          email: ""
          password: ""

        admin_hotel:
          email: ""
          password: ""

        employee:
          email: ""
          password: ""

    south:
      role_auth_data:
        admin_mrf:
          email: ""
          password: ""

        admin_hotel:
          email: ""
          password: ""

        employee:
          email: ""
          password: ""

    nw:
      role_auth_data:
        admin_mrf:
          email: ""
          password: ""

        admin_hotel:
          email: ""
          password: ""

        employee:
          email: ""
          password: ""
